jenkinsci/checkmarx-plugin

- src/main/java/com/checkmarx/jenkins/CxWebService.java
The console contains redundant logs, and some of our larger projects are flooded with this repetition.  This addresses a **few** culprit log messages by comparing the message to the previous message, and suppressing if equal.  Example:
> Scan job waiting for processing
> Scan job waiting for processing
> Scan job waiting for processing
> Scan job waiting for processing
> Scan job waiting for processing
> Scan job waiting for processing
> Scan job waiting for processing
> Source contains: 10387 lines of code.
> Scan job queued at position: 1
> Scan job queued at position: 1
> Scan job queued at position: 1
> Scan job queued at position: 1
> Scanning: Engine starts scan  (Current stage progress: 0%, Total progress: 0%)
> Scanning: Engine starts scan  (Current stage progress: 0%, Total …
> prevent repetitive logging

- src/main/java/com/checkmarx/jenkins/CxScanBuilder.java
- src/main/java/com/checkmarx/jenkins/EnvVarAction.java
This allows for simple customization of notifications in other plugins and build steps.
> set results to environment variables

- src/main/java/com/checkmarx/jenkins/CxScanBuilder.java
> To close the issue #AB1976

- build.gradle
- gradle.properties
- src/main/java/com/checkmarx/jenkins/CxLoggerAdapter.java
- src/main/java/com/checkmarx/jenkins/CxScanBuilder.java
- src/main/java/com/checkmarx/jenkins/CxScanCallable.java
- src/main/java/com/checkmarx/jenkins/DependencyScanConfig.java
- src/main/resources/com/checkmarx/jenkins/CxScanBuilder/config.jelly
- src/main/resources/com/checkmarx/jenkins/CxScanBuilder/global.jelly
- src/main/resources/com/checkmarx/jenkins/CxScanBuilder/help-addGlobalCommenToBuildCommet.html
- src/main/resources/com/checkmarx/jenkins/CxScanBuilder/help-hideDebugLogs.html
- src/main/resources/com/checkmarx/jenkins/CxScanBuilder/help-isExploitablePath.html
- src/main/resources/com/checkmarx/jenkins/CxScanBuilder/help-isIncludeSources.html
- src/main/resources/com/checkmarx/jenkins/CxScanBuilder/help-sastcomment.html
- src/main/resources/com/checkmarx/jenkins/CxScanBuilder/help-scaConfigFile.html
- src/main/resources/com/checkmarx/jenkins/CxScanBuilder/help-scaEnvVariables.html
- src/main/resources/com/checkmarx/jenkins/CxScanBuilder/help-useGlobalSastDetails.html
- src/main/resources/com/checkmarx/jenkins/CxScanBuilder/help-useSastDetails.html
This release includes the SCA features for Jenkins and the vulnerability fixes
> Sca features vulfixes

- build.gradle
- gradle.properties
- src/main/resources/META-INF/hudson.remoting.ClassFilter
1) Changes for FSA Update.
2) Changes for Language support for HTML Report
> Code changes for  FSA Update

- build.gradle
- gradle.properties
- src/main/resources/META-INF/hudson.remoting.ClassFilter
Merging code change for latest common
> Change for version increment for latest common

- src/main/java/com/checkmarx/jenkins/CxScanBuilder.java
- src/main/resources/com/checkmarx/jenkins/CxScanBuilder/config.jelly
- src/main/resources/com/checkmarx/jenkins/CxScanBuilder/help-postScanActionId.html
Adding Post Scan update functionallity
> 2872 post scan update

- src/main/java/com/checkmarx/jenkins/CxScanBuilder.java
- src/main/resources/com/checkmarx/jenkins/CxScanBuilder/config.jelly
- src/main/resources/com/checkmarx/jenkins/CxScanBuilder/help-customFields.html
- src/main/resources/com/checkmarx/jenkins/CxScanBuilder/help-forceScan.html
Other comments to be added by Carlos
Handled the validations for selecting both incremental and force scan
If both options selected stop the scan by throwing exception . The same exception is thrown which will be re-thrown by the overridden method perform ()
> 2700 2819 custom fields force scan

- src/main/java/com/checkmarx/jenkins/CxScanBuilder.java
This change is to sort Team List used to show in Drop down Alphabetically
> feature: sorting teams list for dropdown

- src/main/resources/com/checkmarx/jenkins/CxScanBuilder/help-scaTimeout
Added help file for SCA time out feaure
> Added help file for SCA time out

- gradle.properties
- src/main/java/com/checkmarx/jenkins/CxScanBuilder.java
- src/main/resources/com/checkmarx/jenkins/CxScanBuilder/config.jelly
- src/main/resources/com/checkmarx/jenkins/CxScanBuilder/global.jelly
In this PR, we making sure that Form Validations are handled as per the guidelines. Fields  of type optional lock (1 occurrence) and checkbox(1 occurrence) are skipped. 
Verified that all form validations, validate button requests are going over POST.
Verified that those fields where checkMethod is not supported are skipped from the changes.
> Handle formvalidations and perform permission checks

- build.gradle
- src/main/java/com/checkmarx/jenkins/CxScanBuilder.java
1. Upgrade common-client
2. Fixed bug for PostScanAction
> Changes for common upgrade and fix bug

- src/main/java/com/checkmarx/jenkins/CxConnectionDetails.java
- src/main/java/com/checkmarx/jenkins/CxScanBuilder.java
Added SCA proxy support when user does not want to use proxy for SAST and only for SCA proxy to be used
> Add sca proxy support

- build.gradle
- gradle.properties
- src/main/java/com/checkmarx/jenkins/CxScanBuilder.java
- src/main/java/com/checkmarx/jenkins/DependencyScanConfig.java
- src/main/resources/META-INF/hudson.remoting.ClassFilter
This PR fixes PLUG-736, PLUG-622, PLUG-619, PLUG-618, PLUG-613, PLUG-396
* Suppress benign errors by default (for ex. duplicate scan or timeout error). This can be disabled by defined JVM property 'suppressBenignErrors=false'
* Special character validation for custom field
* Introduced presetId 0 that makes SAST use presetid of previous scan of that project. If it is a new project, preset gets defaulted at SAST to 'Checkmarx Default'
* Pipeline script can be configured with scaTeamId instead of scaTeamPath. scaTeamId takes precedence.
* CxOrigin value now contains Jenkin's Plugin Version
Tests:
1.	It now shows FAILURE with message 
a.	when job is cancelled from the SAST server  (Delete scan in SAST while plugin is waiting for results)
b.	when incremental scan results with ‘Incremental …
> Jenkins plugin enhancements and fixes

- gradle.properties
- src/main/java/com/checkmarx/jenkins/CxScanBuilder.java
This PR fixes the null pointer exception issue where if parameter for customField is not part of the scripted pipeline definition.  This never occurs in freestyle job. 
- [ X] Make sure you are opening from a **topic/feature/bugfix branch** (right side) and not your main branch!
- [ X] Ensure that the pull request title represents the desired changelog entry
- [X ] Please describe what you did
- [ X] Link to relevant issues in GitHub or Jira
- [ X] Link to relevant pull requests, esp. upstream and downstream changes
- [ X] Ensure you have provided tests - that demonstrates feature works or fixes the issue
> Fix custom field verification NPE issue

- src/main/java/com/checkmarx/jenkins/CxScanBuilder.java
- src/main/java/com/checkmarx/jenkins/CxScanResult.java
- src/main/resources/com/checkmarx/jenkins/CxScanBuilder/global.jelly
> Report generation

- src/main/java/com/checkmarx/jenkins/CxScanBuilder.java
https://checkmarx.atlassian.net/browse/PLUG-932
> Fixed build status while threshold exceeded in SCA 

- src/main/java/com/checkmarx/jenkins/CxScanBuilder.java
- src/main/resources/com/checkmarx/jenkins/CxScanBuilder/config.jelly
- src/main/resources/com/checkmarx/jenkins/CxScanBuilder/global.jelly
- src/main/resources/com/checkmarx/jenkins/CxScanBuilder/help-enableDataRetention.html
Plugin51 
->Setting Data Retention Rate for new projects
> add retention rate settings

- src/main/java/com/checkmarx/jenkins/CxScanBuilder.java
Ref:  https://checkmarx.atlassian.net/browse/PLUG-633
https://checkmarx.atlassian.net/browse/PLUG-776
> Merged Code from bug_776_latest branch

- build.gradle
- src/main/java/com/checkmarx/jenkins/CxScanBuilder.java
- src/main/java/com/checkmarx/jenkins/DependencyScanConfig.java
- src/main/resources/com/checkmarx/jenkins/CxScanBuilder/config.jelly
- src/main/resources/com/checkmarx/jenkins/CxScanBuilder/global.jelly
- src/main/resources/com/checkmarx/jenkins/CxScanBuilder/help-isExploitablePathByScaResolver.html
- src/main/resources/com/checkmarx/jenkins/CxScanBuilder/help-scaResolverAddParameters.html
Reverts jenkinsci/checkmarx-plugin#121
> Revert "Sca resolver add params"

- build.gradle
- src/main/java/com/checkmarx/jenkins/CxScanBuilder.java
- src/main/java/com/checkmarx/jenkins/DependencyScanConfig.java
- src/main/resources/com/checkmarx/jenkins/CxScanBuilder/config.jelly
- src/main/resources/com/checkmarx/jenkins/CxScanBuilder/global.jelly
- src/main/resources/com/checkmarx/jenkins/CxScanBuilder/help-isExploitablePathByScaResolver.html
- src/main/resources/com/checkmarx/jenkins/CxScanBuilder/help-scaResolverAddParameters.html
> Sca resolver add params

- src/main/java/com/checkmarx/jenkins/CxScanBuilder.java
- src/main/resources/com/checkmarx/jenkins/CxScanBuilder/config.jelly
> warning for 0 retention rate

- src/main/resources/com/checkmarx/jenkins/CxScanBuilder/config.jelly
> Updated title of Checkbox of Generate CxSCA Report

- build.gradle
> Updated org.json version

- gradle.properties
- src/main/java/com/checkmarx/jenkins/CxScanBuilder.java
- src/main/resources/com/checkmarx/jenkins/CxScanBuilder/config.jelly
- src/main/resources/com/checkmarx/jenkins/CxScanBuilder/global.jelly
> bugFix for UI

- src/main/java/com/checkmarx/jenkins/CxScanBuilder.java
> Added error messages in Case of exp path params

- build.gradle
- gradle.properties
- src/main/java/com/checkmarx/jenkins/CxScanBuilder.java
- src/main/java/com/checkmarx/jenkins/CxScanResult.java
- src/main/java/com/checkmarx/jenkins/DependencyScanConfig.java
- src/main/java/com/checkmarx/jenkins/ScaReportFormat.java
- src/main/resources/com/checkmarx/jenkins/CxScanBuilder/config.jelly
- src/main/resources/com/checkmarx/jenkins/CxScanBuilder/global.jelly
- src/main/resources/com/checkmarx/jenkins/CxScanBuilder/help-enableDataRetention.html
- src/main/resources/com/checkmarx/jenkins/CxScanBuilder/help-enableScaResolver.html
- src/main/resources/com/checkmarx/jenkins/CxScanBuilder/help-generateScaReport.html
- src/main/resources/com/checkmarx/jenkins/CxScanBuilder/help-globalScaResolverAddParameters.html
- src/main/resources/com/checkmarx/jenkins/CxScanBuilder/help-isExploitablePathByScaResolver.html
- src/main/resources/com/checkmarx/jenkins/CxScanBuilder/help-isGlobalExploitablePathByScaResolver.html
- src/main/resources/com/checkmarx/jenkins/CxScanBuilder/help-scaResolverAddParameters.html
This release consists: 
• Added functionality to generate Sca Report in various formats, i.e., PDF, XML, CSV, JSON, cyclonedxjson, cyclonedxxml files.
• Added functionality to generate reports in workspace directory of agent.
• Added functionality to generate SCA/OSA reports in workspace directory.
• ScaResolver integration is enhanced to make reuse of SAST specific parameters like project name, source code location, sast server url, credentials and result path. Sca resolver additional parameters is reserved for additional arguments as per sca resolver arguments syntax.
• Enhanced the functionality to provide option to select job status in case of CxSAST vulnerability threshold is crossed.
• Global setting SSL/TLS validation checkbox is enabled by default to enforce TLS/SSL server …
> Release 2023.2.6 changes

- src/main/java/com/checkmarx/jenkins/CxScanBuilder.java
> Warning message fix

- build.gradle
- gradle.properties
- src/main/java/com/checkmarx/jenkins/CxScanBuilder.java
- src/main/java/com/checkmarx/jenkins/CxScanCallable.java
- src/main/java/com/checkmarx/jenkins/DependencyScanConfig.java
- src/main/resources/META-INF/hudson.remoting.ClassFilter
- src/main/resources/com/checkmarx/jenkins/CxScanBuilder/config.jelly
- src/main/resources/com/checkmarx/jenkins/CxScanBuilder/global.jelly
- src/main/resources/com/checkmarx/jenkins/CxScanBuilder/help-enableProjectPolicyEnforcement.html
- src/main/resources/com/checkmarx/jenkins/CxScanBuilder/help-exceptionOnThresholdError.html
- src/main/resources/com/checkmarx/jenkins/CxScanBuilder/help-exceptionOnThresholdErrorGlobal.html
- src/main/resources/com/checkmarx/jenkins/CxScanBuilder/help-projectLevelCustomFields.html
- src/main/resources/com/checkmarx/jenkins/CxScanBuilder/help-scaProjectCustomTags.html
- src/main/resources/com/checkmarx/jenkins/CxScanBuilder/help-scaScanCustomTags.html
Enhanced to use expected versions of SAST APIs
Added support to Enable Policy Enforcement for SAST and SCA separately. (These two needs to be configured separately)
Enhanced the plugin to display correct error message on Checkmarx reports screen if SCA scan policies are violated
Added support for SAST Project Level Custom Fields
Added support for SCA Project Custom Tags
Added support for SCA Scan Custom Tags
Allowed special characters in scan level and project level custom fields for SAST and SCA.
Allowed special characters in Jenkins job name
Added support to propagate vulnerability threshold exceed errors
SCA Agent is no more supported
Enhanced the plugin to support SCA URL in NoProxyHost
Added support for Jenkins Server v2.375.4 and v2.414.3
Fixed deserialization issue for API …
> 2023 q4 integration branch

- build.gradle
- src/main/java/com/checkmarx/jenkins/CxScanBuilder.java
- src/main/java/com/checkmarx/jenkins/CxScanResult.java
- src/main/resources/com/checkmarx/jenkins/CxProjectResult/jobMain.jelly
This PR addresses the following:
**1. [PLUG-1707](https://checkmarx.atlassian.net/browse/PLUG-1707): [Jenkins] Security | RCE vulnerabilities - snakeyaml**
- build.gradle
- Version change: 
Cx-client-common version: **2024.1.1**
- -List of resolved and existing non-exploitable vulnerabilities: **[Jenkins 2024Q2 Vulnerability fixes.xlsx](https://github.com/jenkinsci/checkmarx-plugin/files/14849284/Jenkins.2024Q2.Vulnerability.fixes.xlsx)**
- **[Link for SCA Scan result](https://sca.checkmarx.net/#/projects/6d04f545-32dc-4abf-8bb9-d77fc1e308bc/reports/b1c149e3-94e3-4216-9a18-fe70e11cbf79/packages/all)**
**2. [PLUG-804](https://checkmarx.atlassian.net/browse/PLUG-804): 'force scan parameter' appears twice in build logs**
- CxScanBuilder.java 
Removed duplicated line of code.
**3. …
> Jenkins Release: 2024_Q2: PLUG- 806, 804 and 1707

- build.gradle
Client common version changed.
> Version change (Cx-Client-Common)

- gradle.properties
> Plugin version change

- build.gradle
- gradle.properties
- src/main/java/com/checkmarx/jenkins/CxScanBuilder.java
This PR addresses the following:
**1. [PLUG-1819](https://checkmarx.atlassian.net/browse/PLUG-1819): [Jenkins] if configure pipeline and trigger scan with Asynchronous mode then build getting failed.**
**2. [PLUG-1820](https://checkmarx.atlassian.net/browse/PLUG-1820): [Jenkins] configure job with asynchronous mode and trigger scan. then in 'Cx Reports' shows the last scan failed report.**
- Plugin version changed to **2024.2.2**
- Cx-Client-Common version changed to **2024.2.2**
--------------------------------------------------------------------------------------------------------------------------------
- Reviewer Requests: @ThokalSameer 
--------------------------------------------------------------------------------------------------------------------------------
```[tasklist]
```
> PLUG: 1819, 1820 and version change

- build.gradle
- gradle.properties
Client common and plugin version changed to **2024.2.3** for latest QA release.
> Version Change

- build.gradle
- gradle.properties
- src/main/java/com/checkmarx/jenkins/CxScanBuilder.java
- src/main/java/com/checkmarx/jenkins/CxScanResult.java
- src/main/resources/com/checkmarx/jenkins/CxProjectResult/jobMain.jelly
- src/main/resources/com/checkmarx/jenkins/CxScanBuilder/config.jelly
•	Fixed the issue, CxSCA team with value as 'All users' getting overridden for existing projects. 
•	Fixed the issue , ‘scaReportFormat:PDF’ parameter is present in SCA pipeline script by default even when ‘Generate CxSCA report’ checkbox is disabled.
•	Fixed the issue, if first scan in pipeline/new project is asynchronous, it should not show 'failed scan' report if reports are not generated, or report of previous successful scan is not available.
•	Fixed the issue of pipeline, build failing and showing failed report in case of asynchronous scan, when the previous synchronous scan fails or ‘enable vulnerability threshold exceed’ checkbox is checked but parent checkbox (Enable synchronous mode) is not checked.
•	Added form validation for 'Enable vulnerability threshold' checkbox when …
> Jenkins 2024.2.3 Plugin Release

- build.gradle
- gradle.properties
- src/main/java/com/checkmarx/jenkins/CommonClientFactory.java
- src/main/java/com/checkmarx/jenkins/CxProjectResult.java
- src/main/java/com/checkmarx/jenkins/CxResultSeverity.java
- src/main/java/com/checkmarx/jenkins/CxScanBuilder.java
- src/main/java/com/checkmarx/jenkins/CxScanCallable.java
- src/main/java/com/checkmarx/jenkins/CxScanResult.java
- src/main/java/com/checkmarx/jenkins/EnvVarAction.java
- src/main/java/com/checkmarx/jenkins/RemoteScanInfo.java
- src/main/java/com/checkmarx/jenkins/configascode/SastConfig.java
- src/main/java/com/checkmarx/jenkins/configascode/ScaConfig.java
- src/main/java/com/checkmarx/jenkins/legacy8_7/GetOpenSourceSummaryResponse.java
- src/main/java/com/checkmarx/jenkins/legacy8_7/OsaScanResult.java
- src/main/java/com/checkmarx/jenkins/legacy8_7/SastScanResult.java
- src/main/java/com/checkmarx/jenkins/legacy8_7/ThresholdConfig.java
- src/main/resources/com/checkmarx/jenkins/CxScanBuilder/config.jelly
- src/main/resources/com/checkmarx/jenkins/CxScanBuilder/global.jelly
- src/main/resources/com/checkmarx/jenkins/CxScanBuilder/help-criticalThreshold.html
- src/main/resources/com/checkmarx/jenkins/CxScanBuilder/help-criticalThresholdEnforcement.html
- src/main/resources/com/checkmarx/jenkins/CxScanBuilder/help-osaCriticalThreshold.html
- src/main/resources/com/checkmarx/jenkins/CxScanBuilder/help-osaCriticalThresholdEnforcement.html
This PR contains following changes
•	Enhanced to provide support to Critical Severity. 
•	Enhanced to show SAST server Engine Pack Version in the logs.
•	Enhanced to send plugin name and plugin version in the API request header.
•	Enhanced to support Jenkins version 2.462.1.
•	Upgraded third party libraries to fix vulnerabilities
Multiple rounds of dev testing was done to test above mentioned functionality.
QA progression testing and regression testing was done to provide check all the existing and new functionalities are working properly.
Tested on multiple versions of Jenkins.
Tested with different versions of Cx SAST servers.
> 2024 q3 integration branch

- build.gradle
> Vulnerability Fix

- build.gradle
- gradle.properties
- src/main/java/com/checkmarx/jenkins/CxScanCallable.java
PLUG-2253: Implement Jenkins policy link
> PLUG-2253: Implement Jenkins policy link 
